

export const FETCH_TWITTER_REQUEST = 'FETCH_TWITTER_REQUEST'
export const FETCH_TWITTER_SUCCES = 'FETCH_TWITTER_SUCCES'

export const FETCH_TWITTER_AGREGAT_REQUEST = 'FETCH_TWITTER_AGREGAT_REQUEST'
export const FETCH_TWITTER_AGREGAT_FAIL = 'FETCH_TWITTER_AGREGAT_FAIL'
export const FETCH_TWITTER_AGREGAT_SUCCES = 'FETCH_TWITTER_AGREGAT_SUCCES'
