

export const FETCH_TWITTER_REQUEST = 'FETCH_TWITTER_REQUEST'
export const FETCH_TWITTER_SUCCES = 'FETCH_TWITTER_SUCCES'
export const FETCH_TWITTER_FAIL ='FETCH_TWITTER_FAIL'
export const FETCH_TWITTER_AGREGAT_REQUEST = 'FETCH_TWITTER_AGREGAT_REQUEST'
export const FETCH_TWITTER_AGREGAT_FAIL = 'FETCH_TWITTER_AGREGAT_FAIL'
export const FETCH_TWITTER_AGREGAT_SUCCES = 'FETCH_TWITTER_AGREGAT_SUCCES'
export const FETCH_TWITTER_TEAM_REQUEST="FETCH_TWITTER_TEAM_REQUEST"
export const FETCH_TWITTER_TEAM_FAIL="FETCH_TWITTER_TEAM_FAIL"
export const FETCH_TWITTER_TEAM_SUCCES="FETCH_TWITTER_TEAM_SUCCES"
